import { useDeferredValue, useEffect, useMemo, useRef, useState, type CSSProperties } from 'react';
import { Button, Dialog, Input } from '../shared/ui';
import { Textarea } from '../components/ui/textarea';
import { Select, Help } from '../shared/controls';
import { Choice, TextField } from './fields';
import { host, readonly, write } from './api';
import { clone, entries, importWeb, moveNodes, removeNodes, renameCategory, memoTree, type MemoBranch, type Bag, type Memo, type WebNode } from './model';
import { useTreeView } from './useTreeView';
import { SettingsStore, useSettings } from './store';

export function WebCatalog({ store }: { store: SettingsStore }) {
  const s = useSettings(store), nodes: WebNode[] = s.config!.plugins.web.settings.items;
  const [selected, setSelected] = useState<string[]>([]), [expanded, setExpanded] = useState<Set<string>>(() => new Set(nodes.map(n => n.id))), [filter, setFilter] = useState(''), [target, setTarget] = useState(''), [pending, setPending] = useState<Bag | null>(null), [overwrite, setOverwrite] = useState('skip'), [deleteOpen, setDeleteOpen] = useState(false), [pendingAdd, setPendingAdd] = useState('');
  const deferred = useDeferredValue(filter).trim().toLowerCase(), all = useMemo(() => entries(nodes), [nodes]);
  const node = all.find(e => e.node.id === selected[0])?.node;
  const dragging = useRef('');
  useEffect(() => { if (s.webSelection) { setSelected([s.webSelection]); setExpanded(prev => new Set([...prev, ...all.filter(e => entries(e.node.children || []).some(child => child.node.id === s.webSelection)).map(e => e.node.id)])); } }, [s.webSelection]);
  const visible = useMemo(() => {
    const matched = new Set(all.filter(e => [e.node.title, e.node.url, e.node.note, e.node.id].join(' ').toLowerCase().includes(deferred)).map(e => e.node.id));
    const list: typeof all = [];
    const visit = (items: WebNode[], depth: number, parent: WebNode | null) => items.forEach(node => {
      if (deferred && !matched.has(node.id) && !entries(node.children || []).some(e => matched.has(e.node.id))) return;
      list.push({ node, depth, parent }); if (deferred || expanded.has(node.id)) visit(node.children || [], depth + 1, node);
    }); visit(nodes, 0, null); return list;
  }, [all, nodes, deferred, expanded]);
  const view = useTreeView(visible.map(e => e.node.id), selected[0] || '', deferred);
  const [width, setWidth] = useState(() => { try { return Number(localStorage.getItem('flowhub:web-tree-width')) || 260; } catch { return 260; } });
  const resizing = useRef<{ x: number; width: number } | null>(null);
  function resize(value: number) { const next = Math.max(220, Math.min(380, value)); setWidth(next); if (!readonly()) try { localStorage.setItem('flowhub:web-tree-width', String(next)); } catch { /* presentation only */ } }
  const plan = useMemo(() => pending ? importWeb(nodes, pending.items, overwrite === 'overwrite') : null, [nodes, pending, overwrite]);
  const editNodes = (next: WebNode[]) => store.edit(c => { c.plugins.web.settings.items = next; });
  function add(where: 'root' | 'child' | 'sibling') {
    const id = `node-${crypto.randomUUID()}`; const next = clone(nodes), context = entries(next).find(e => e.node.id === node?.id);
    const added = { id, title: '新节点', children: [] };
    if (where === 'child' && context) { (context.node.children ||= []).push(added); setExpanded(prev => new Set([...prev, context.node.id])); }
    else if (where === 'sibling' && context) { const siblings = context.parent?.children || next; siblings.splice(siblings.indexOf(context.node) + 1, 0, added); }
    else next.push(added);
    editNodes(next); setSelected([id]); setPendingAdd(id);
  }
  function move(boundary: 'top' | 'up' | 'down' | 'bottom') {
    const context = all.find(e => e.node.id === node?.id); if (!context) return;
    const siblings = context.parent?.children || nodes, index = siblings.indexOf(context.node);
    const nextIndex = boundary === 'top' ? 0 : boundary === 'bottom' ? siblings.length - 1 : index + (boundary === 'up' ? -1 : 1);
    if (nextIndex < 0 || nextIndex >= siblings.length || nextIndex === index) return;
    editNodes(moveNodes(nodes, [context.node.id], siblings[nextIndex].id, nextIndex < index ? 'before' : 'after'));
  }
  function select(id: string, multi: boolean) { setSelected(prev => multi ? prev.includes(id) ? prev.filter(v => v !== id) : [id, ...prev] : [id]); }
  return <div className="grid gap-4"><div className="flex flex-wrap gap-2"><Button onClick={() => add('root')}>＋ 一级节点</Button><Button disabled={!node} onClick={() => add('child')}>子节点</Button><Button disabled={!node} onClick={() => add('sibling')}>同级节点</Button>{pendingAdd ? <Button onClick={() => { editNodes(removeNodes(nodes, [pendingAdd])); setPendingAdd(''); setSelected([]); }}>取消添加</Button> : null}<Button onClick={() => void store.run(async () => { const result = await write('pickWebImport'); if (!result.canceled) { if (!result.items?.length) throw new Error('导入文件里没有网页节点'); setPending(result); } })}>导入目录…</Button><Button onClick={() => setExpanded(new Set(all.map(e => e.node.id)))}>全部展开</Button><Button onClick={() => setExpanded(new Set())}>全部收起</Button></div>
    <div className="settings-collection grid gap-4" style={{ '--settings-tree-width': `${width}px` } as CSSProperties}><aside className="min-w-0"><Input aria-label="筛选网页目录" type="search" placeholder="标题、域名或节点 ID" value={filter} onChange={e => setFilter(e.target.value)} /><div ref={view.ref} onScroll={view.capture} role="tree" aria-label="网页目录" aria-multiselectable="true" className="settings-tree mt-2">{visible.map(({ node: item, depth }) => <div key={item.id} role="treeitem" aria-level={depth + 1} aria-selected={selected.includes(item.id)} aria-expanded={item.children?.length ? expanded.has(item.id) : undefined} tabIndex={0} data-node-id={item.id} className="settings-tree-row flex items-center gap-1" style={{ paddingInlineStart: 8 + depth * 16 }} draggable={!readonly()} onClick={e => select(item.id, e.metaKey || e.ctrlKey || e.shiftKey)} onKeyDown={e => { if (['Enter', ' '].includes(e.key)) { e.preventDefault(); select(item.id, e.metaKey || e.ctrlKey || e.shiftKey); } if (e.key === 'ArrowRight') setExpanded(prev => new Set([...prev, item.id])); if (e.key === 'ArrowLeft') setExpanded(prev => { const next = new Set(prev); next.delete(item.id); return next; }); if (['ArrowDown', 'ArrowUp'].includes(e.key)) { e.preventDefault(); const rows = e.currentTarget.parentElement?.querySelectorAll<HTMLElement>('[role=treeitem]'); const index = visible.findIndex(n => n.node.id === item.id); rows?.[index + (e.key === 'ArrowDown' ? 1 : -1)]?.focus(); } }} onDragStart={e => { dragging.current = item.id; e.dataTransfer.setData('text/flowhub-node', item.id); }} onDragEnd={() => { dragging.current = ''; }} onDragOver={e => { if (dragging.current) e.preventDefault(); }} onDrop={e => { e.preventDefault(); const source = dragging.current; if (!source) return; const rect = e.currentTarget.getBoundingClientRect(), fraction = (e.clientY - rect.top) / rect.height; const position = fraction < .25 ? 'before' : fraction > .75 ? 'after' : 'inside'; editNodes(moveNodes(nodes, selected.includes(source) ? selected : [source], item.id, position)); setExpanded(prev => new Set([...prev, item.id])); dragging.current = ''; }}>
      {item.children?.length ? <Button aria-label={`${expanded.has(item.id) ? '收起' : '展开'} ${item.title}`} onClick={e => { e.stopPropagation(); setExpanded(prev => { const next = new Set(prev); if (next.has(item.id)) next.delete(item.id); else next.add(item.id); return next; }); }}>{expanded.has(item.id) ? '▾' : '▸'}</Button> : <span aria-hidden="true">{item.url ? '↗' : '▱'}</span>}<Button aria-label={`拖动 ${item.title || item.id}`} className="settings-drag-handle" onClick={e => e.stopPropagation()} onPointerDown={e => { e.stopPropagation(); dragging.current = item.id; e.currentTarget.setPointerCapture(e.pointerId); }} onPointerUp={e => { e.stopPropagation(); const row = document.elementFromPoint(e.clientX, e.clientY)?.closest<HTMLElement>('[data-node-id]'); if (row && dragging.current) { const rect = row.getBoundingClientRect(), ratio = (e.clientY - rect.top) / rect.height; editNodes(moveNodes(nodes, selected.includes(dragging.current) ? selected : [dragging.current], row.dataset.nodeId!, ratio < .25 ? 'before' : ratio > .75 ? 'after' : 'inside')); setExpanded(prev => new Set([...prev, row.dataset.nodeId!])); } dragging.current = ''; }} onPointerCancel={() => { dragging.current = ''; }}>⠿</Button><span className="truncate">{item.title || item.id}</span></div>)}{!visible.length ? <p>没有匹配目录</p> : null}</div></aside><div className="settings-divider" role="separator" tabIndex={0} aria-label="调整目录宽度" aria-orientation="vertical" aria-valuemin={220} aria-valuemax={380} aria-valuenow={width} onPointerDown={e => { resizing.current = { x: e.clientX, width }; e.currentTarget.setPointerCapture(e.pointerId); }} onPointerMove={e => { if (resizing.current) resize(resizing.current.width + e.clientX - resizing.current.x); }} onPointerUp={() => { resizing.current = null; }} onPointerCancel={() => { resizing.current = null; }} onDoubleClick={() => resize(260)} onKeyDown={e => { const value = { ArrowLeft: width - 10, ArrowRight: width + 10, Home: 220, End: 380 }[e.key]; if (value !== undefined) { e.preventDefault(); resize(value); } }} />
      <div className="min-w-0"><div className="flex flex-wrap gap-2">{(['top', 'up', 'down', 'bottom'] as const).map((id, i) => <Button key={id} disabled={!node} onClick={() => move(id)}>{['顶部', '上移', '下移', '底部'][i]}</Button>)}<Button disabled={!selected.length} onClick={() => setDeleteOpen(true)}>删除 {selected.length || ''}</Button><Help label="拖拽与多选">⌘ / Ctrl / Shift 点击多选。拖到行上方或下方排序，中央作为子节点；也可使用移动目标和排序按钮。</Help></div><div className="flex flex-wrap gap-2 mt-2"><Select label="移动目标" value={target} options={[{ value: '', label: '根目录' }, ...all.filter(e => !selected.includes(e.node.id)).map(e => ({ value: e.node.id, label: `${'　'.repeat(e.depth)}${e.node.title || e.node.id}` }))]} onChange={setTarget} /><Button disabled={!selected.length} onClick={() => editNodes(moveNodes(nodes, selected, target))}>移动所选</Button></div>
        {node ? <>{(['title', 'id', 'url', 'icon', 'accent', 'note'] as const).map((key, i) => <TextField key={key} label={['标题', '节点 ID', '页面链接', '图标（Emoji / 图片 URL）', '强调色', '备注'][i]} value={node[key]} readOnly={key === 'id'} onChange={v => store.edit(c => { const target = entries(c.plugins.web.settings.items).find(e => e.node.id === node.id); if (target) target.node[key] = v; })} help={key === 'url' ? '留空作为目录，填写后可直接打开，也可保留子节点。' : undefined} />)}</> : <p>选择目录或添加新节点</p>}
      </div></div>
    {deleteOpen ? <Dialog title="删除节点" busy={false} onClose={() => setDeleteOpen(false)}><p>删除选中的 {selected.length} 个节点及其子节点？保存前可撤销。</p><Button onClick={() => { editNodes(removeNodes(nodes, selected)); setSelected([]); setDeleteOpen(false); }}>确认删除</Button></Dialog> : null}
    {pending && plan ? <Dialog title="核对目录导入" busy={false} onClose={() => setPending(null)}><p>{pending.path}</p><Choice label="重复 ID" value={overwrite} options={[{ value: 'skip', label: '跳过' }, { value: 'overwrite', label: '覆盖属性并合并子节点' }]} onChange={setOverwrite} /><pre className="settings-code">{plan.changes.join('\n')}</pre><Button onClick={() => { editNodes(plan.nodes); setPending(null); }}>应用为草稿</Button></Dialog> : null}
  </div>;
}
export function Memos({ store }: { store: SettingsStore }) {
  const s = useSettings(store), configured = s.config!.plugins.memo.settings.items;
  const defaults = useMemo(() => host().FlowHubMemoCatalog?.cloneDefaults() || [], []);
  const items: Memo[] = configured || defaults;
  const [selected, setSelected] = useState(''), [filter, setFilter] = useState(''), [collapsed, setCollapsed] = useState(new Set<string>()), [category, setCategory] = useState<string | null>(null), [tags, setTags] = useState<string | null>(null), [confirm, setConfirm] = useState<'reset' | 'delete' | null>(null);
  const deferred = useDeferredValue(filter).toLowerCase(), current = items.find(i => i.id === selected) || items[0];
  const tree = memoTree(items.filter(item => [item.title, item.category, item.content, item.description, ...(Array.isArray(item.tags) ? item.tags : [])].join(' ').toLowerCase().includes(deferred)));
  function selectMemo(id: string) { setSelected(id); setCategory(null); setTags(null); }
  function edit(action: (items: Memo[]) => void) { store.edit(c => { c.plugins.memo.settings.items ||= clone(defaults); action(c.plugins.memo.settings.items); }); }
  return <><div className="flex flex-wrap gap-2 mb-4"><Button onClick={() => { const id = `memo-${crypto.randomUUID()}`; edit(items => items.push({ id, title: '新备忘', category: '其他', content: '', tags: [] })); setSelected(id); }}>新增备忘</Button><Button onClick={() => setConfirm('reset')}>恢复内置</Button><span>{items.length} 条 · {configured ? '自定义库' : '内置命令库'}</span></div><div className="grid gap-4 md:grid-cols-[minmax(220px,1fr)_2fr]"><aside><Input aria-label="筛选备忘录" value={filter} onChange={e => setFilter(e.target.value)} placeholder="搜索备忘…" /><MemoTreeView branch={tree} collapsed={collapsed} forceOpen={Boolean(deferred)} selected={current?.id || ''} onSelect={selectMemo} onToggle={path => setCollapsed(prev => { const next = new Set(prev); if (next.has(path)) next.delete(path); else next.add(path); return next; })} /></aside><div className="min-w-0">{current ? <><TextField label="标题" value={current.title} onChange={v => edit(items => { items.find(i => i.id === current.id)!.title = v; })} /><div onBlur={event => { if (event.currentTarget.contains(event.relatedTarget as Node)) return; if (category !== null && category !== current.category) { const before = current.category || ''; edit(items => { const item = items.find(i => i.id === current.id)!; item.category = category; renameCategory(items, before, category, item.id); }); setCollapsed(prev => new Set([...prev].map(path => path === before || path.startsWith(`${before} / `) ? category + path.slice(before.length) : path))); setCategory(null); } }}><TextField label="分类路径" value={category ?? current.category} onChange={setCategory} help="使用 / 分层；离开输入框时同步修改后代分类路径。" /></div><label className="grid gap-2">命令或备忘内容<Textarea className="settings-code" rows={12} spellCheck={false} value={current.content || ''} onChange={e => edit(items => { items.find(i => i.id === current.id)!.content = e.target.value; })} /></label><TextField label="说明" value={current.description} onChange={v => edit(items => { items.find(i => i.id === current.id)!.description = v; })} /><div onBlur={() => { if (tags !== null) { edit(items => { items.find(i => i.id === current.id)!.tags = tags.split(/[,，]/).map(v => v.trim()).filter(Boolean); }); setTags(null); } }}><TextField label="搜索标签" value={tags ?? (Array.isArray(current.tags) ? current.tags.join(', ') : current.tags || '')} onChange={setTags} /></div><Button onClick={() => setConfirm('delete')}>删除备忘</Button></> : <p>暂无备忘录</p>}</div></div>{confirm ? <Dialog title={confirm === 'reset' ? '恢复内置备忘录' : '删除备忘'} busy={false} onClose={() => setConfirm(null)}><p>{confirm === 'reset' ? '当前自定义备忘录将替换为内置库；保存前可撤销。' : '删除当前备忘录？保存前可撤销。'}</p><Button onClick={() => { if (confirm === 'reset') store.edit(c => { delete c.plugins.memo.settings.items; }); else if (current) edit(items => { const index = items.findIndex(i => i.id === current.id); if (index >= 0) items.splice(index, 1); }); setConfirm(null); }}>确认</Button></Dialog> : null}</>;
}

function MemoTreeView({ branch, collapsed, forceOpen, selected, onSelect, onToggle }: { branch: MemoBranch; collapsed: Set<string>; forceOpen: boolean; selected: string; onSelect: (id: string) => void; onToggle: (path: string) => void }) {
  return <div>{branch.children.map(child => { const open = forceOpen || !collapsed.has(child.path); return <div key={child.path} className="settings-memo-branch"><Button aria-expanded={open} data-memo-category={child.path} onClick={() => onToggle(child.path)}>{open ? '▾' : '▸'} {child.name} · {child.count}</Button>{open ? <MemoTreeView branch={child} collapsed={collapsed} forceOpen={forceOpen} selected={selected} onSelect={onSelect} onToggle={onToggle} /> : null}</div>; })}{branch.items.map(item => <Button className="settings-memo-row" aria-pressed={selected === item.id} key={item.id} onClick={() => onSelect(item.id)}>{item.title}</Button>)}</div>;
}
