import { useEffect, useState, type ReactNode } from 'react';
import { Button, Dialog, Input, Tabs } from '../shared/ui';
import { Help, Switch } from '../shared/controls';
import { Choice, Row, Shortcut, TextField, Toggle } from './fields';
import { call, host, readonly, write } from './api';
import { diff, imported, tools, clipboardLimit, hasExclusions, type Bag } from './model';
import { SettingsStore, useSettings } from './store';
export const sections = [
  { id: 'general', label: '基础' },
  { id: 'search', label: '搜索入口' },
  { id: 'network', label: '网络' },
  { id: 'menubar', label: '菜单栏' },
  { id: 'notifications', label: '通知' },
  { id: 'data', label: '数据与诊断' },
  { id: 'updates', label: '更新' },
];
const names: Record<string, string> = { all: '全部', app: '应用', web: '网页目录', clipboard: '剪贴板', memo: '备忘录', tools: '工具' };
export function PathControl({ store, storage = false }: { store: SettingsStore; storage?: boolean }) {
  const s = useSettings(store), config = s.config!;
  const value = storage ? config.plugins.clipboard.settings.storagePath || '' : config.core.configPath || '';
  const info = storage ? s.storage : s.configPath;
  return <Row label={storage ? '数据库与剪贴板目录' : '配置文件位置'} help={storage ? '保存后：空目录接收当前全部数据；已有数据库则加载目标数据，不合并源网页草稿。恢复默认位置也遵循此规则。' : '保存后切换配置文件，原文件保留。'}><div className="grid gap-2"><Input aria-label="路径" title={value || info.defaultPath || info.resolvedPath || '默认位置'} value={value || info.defaultPath || info.resolvedPath || '默认位置'} readOnly /><div className="flex flex-wrap gap-2"><Button onClick={() => void store.run(async () => { const editing = store.snapshot().config; const result = await write(storage ? 'chooseClipboardStorage' : 'chooseConfigPath'); if (store.snapshot().config !== editing) throw new Error('配置已改变，请重新选择位置'); if (!result.canceled && result.path) store.edit(c => { if (storage) c.plugins.clipboard.settings.storagePath = result.path; else c.core.configPath = result.path; }); })}>选择…</Button><Button onClick={() => void store.run(async () => { if (value !== (info.configuredPath || '')) throw new Error('请先保存位置修改，再打开'); await write(storage ? 'openClipboardStorage' : 'openConfigPath'); })}>打开位置</Button><Button onClick={() => store.edit(c => { if (storage) c.plugins.clipboard.settings.storagePath = ''; else c.core.configPath = ''; })}>恢复默认</Button></div></div></Row>;
}
export function DataPanel({ store }: { store: SettingsStore }) {
  const s = useSettings(store), [scope, setScope] = useState('all'), [pending, setPending] = useState<Bag | null>(null), [mode, setMode] = useState('merge'), [preview, setPreview] = useState<Bag | null>(null), [restore, setRestore] = useState(''), [report, setReport] = useState(''), [clearSampling, setClearSampling] = useState(false);
  let changes: string[] = [], importError = '';
  if (pending) { try { changes = diff(s.config, imported(s.config!, pending, mode as 'merge' | 'replace')); } catch (e) { importError = String(e); } }
  return <div className="settings-data-panel">
    <div className="settings-group"><PathControl store={store} /></div>
    <div className="settings-group"><Row label="配置历史" help="每次保存前自动备份上一版；恢复前会再次备份。系统集成类改动可能需要重启。"><Button onClick={() => void store.refreshHistory()}>刷新历史</Button></Row>
    {s.history.error ? <p role="alert">{s.history.error}</p> : null}
    {!s.history.entries?.length ? <p>{s.history.available === false ? '浏览器预览不提供配置历史' : '暂无历史版本'}</p> : (s.history.entries as Bag[]).map(entry => <div className="settings-row flex flex-wrap items-center justify-between gap-2" key={entry.id}><span>{new Date(entry.created_at).toLocaleString()} · {entry.catalog_count || 0} 项 · {entry.bytes} B</span><div className="flex gap-2"><Button onClick={() => void store.run(async () => { setPreview(await call('previewConfigHistory', entry.id)); })}>预览</Button><Button onClick={() => setRestore(entry.id)}>恢复</Button></div></div>)}
    </div>
    {preview ? <Dialog title="历史预览" busy={false} onClose={() => setPreview(null)}><pre className="settings-code">{JSON.stringify(preview.config, null, 2)}</pre></Dialog> : null}
    {restore ? <Dialog title="恢复配置历史" notice={s.error ? s.notice : undefined} busy={s.busy} onClose={() => setRestore('')}><p>将替换当前配置并放弃编辑器中的未保存修改。当前已保存配置会先备份；系统集成可能需要重启。</p><Button disabled={s.busy} onClick={() => void store.run(async () => { await store.restoreHistory(restore); setRestore(''); })}>确认恢复</Button></Dialog> : null}
    <div className="settings-group"><Choice label="导出范围" value={scope} options={[{ value: 'all', label: '全部配置' }, { value: 'core', label: '全局设置' }, ...Object.keys(s.config!.plugins).sort().map(value => ({ value, label: names[value] || value }))]} onChange={setScope} />
    <div className="flex flex-wrap gap-2"><Button onClick={() => void store.run(async () => { const result = await write('exportConfig', scope); store.notice(result.canceled ? '已取消导出' : `已导出到 ${result.path}`); })}>导出配置…</Button><Button onClick={() => void store.run(async () => { const result = await write('pickConfigImport'); if (!result.canceled) { setPending(result); setMode('merge'); } })}>导入配置…</Button></div>
    </div>
    {pending ? <Dialog title="核对导入差异" busy={false} onClose={() => setPending(null)}><p>{pending.path} · 范围 {pending.scope || 'all'}</p>{pending.appVersion && pending.currentAppVersion !== pending.appVersion ? <p role="status">导出版本 {pending.appVersion} 与当前版本不同，请核对字段。</p> : null}<Choice label="导入方式" value={mode} options={[{ value: 'merge', label: '递归合并（数组替换）' }, { value: 'replace', label: '替换所选范围' }]} onChange={setMode} /><pre className="settings-code">{importError || changes.join('\n') || '没有变化'}</pre><Button disabled={Boolean(importError)} onClick={() => void store.run(async () => { store.replace(imported(s.config!, pending, mode as 'merge' | 'replace')); setPending(null); })}>应用为草稿</Button></Dialog> : null}
    <div className="settings-group"><Toggle label="性能采样" checked={s.diagnostics.enabled === true} onChange={enabled => void store.run(async () => { const result = await write('setDiagnosticsEnabled', enabled); store.patch({ diagnostics: { ...s.diagnostics, ...result, enabled } }); host().flowhubPerformance?.enable(enabled); })} help="记录本机 FlowHub 与 WebKit 资源使用，不上传网络。" />
    <p className="break-all">{s.diagnostics.path || '仅桌面 App 可用'}</p><div className="flex flex-wrap gap-2"><Button onClick={() => void store.run(async () => { const result = await write('sampleDiagnostics'); store.notice(result.reason || '已记录性能采样'); })}>采样一次</Button><Button onClick={() => setClearSampling(true)}>清理采样</Button><Button onClick={() => setReport(JSON.stringify(host().flowhubPerformance?.report(), null, 2))}>界面测量</Button><Button onClick={() => { host().flowhubPerformance?.reset(); setReport(''); }}>重置测量</Button></div>{report ? <pre className="settings-code">{report}</pre> : null}{clearSampling ? <Dialog title="清理性能采样" busy={s.busy} onClose={() => setClearSampling(false)}><p>只清理本机性能记录，不影响网页、剪贴板或备忘录数据。</p><Button onClick={() => void store.run(async () => { await write('clearDiagnostics'); setClearSampling(false); store.notice('性能数据已清理'); })}>确认清理</Button></Dialog> : null}
    </div>
  </div>;
}
export function Core({ store, section, onSection, actions }: { store: SettingsStore; section: string; onSection: (id: string) => void; actions?: ReactNode }) {
  const s = useSettings(store), c = s.config!, core = c.core;
  const setCore = (key: string, value: unknown) => store.edit(c => { c.core[key] = value; });
  const setNested = (key: string, field: string, value: boolean) => store.edit(c => { c.core[key][field] = value; });
  const savedOrder = Array.isArray(core.searchResultOrder) ? core.searchResultOrder as string[] : [];
  const order = [...new Set([...savedOrder, ...(core.webBeforeClipboard === false ? ['app', 'clipboard', 'web', 'memo'] : ['app', 'web', 'clipboard', 'memo'])])].filter(id => ['app', 'web', 'clipboard', 'memo'].includes(id));
  const searchPlugins = [...order.flatMap(id => s.plugins.filter(plugin => plugin.id === id)), ...s.plugins.filter(plugin => !order.includes(plugin.id))];
  const [draggingSource, setDraggingSource] = useState('');
  const [dropSource, setDropSource] = useState('');
  const moveOrder = (id: string, index: number) => { if (index < 0 || index >= order.length || !order.includes(id)) return; const next = order.filter(v => v !== id); next.splice(index, 0, id); setCore('searchResultOrder', next); };
  useEffect(() => { if (section !== 'menubar' || readonly()) return; const refresh = () => void store.run(() => store.refreshMenu()); refresh(); window.addEventListener('focus', refresh); return () => window.removeEventListener('focus', refresh); }, [section, store]);
  const previewInspect = readonly() && section === 'network';
  return <><div className="settings-core-toolbar"><Tabs label="通用设置分类" items={sections} value={section} onChange={onSection} />{actions ? <div className="settings-core-actions">{actions}</div> : null}</div><fieldset disabled={s.busy || s.conflict || (readonly() && !previewInspect)} className="settings-fieldset"><section role="tabpanel" id={`panel-${section}`} aria-labelledby={`tab-${section}`}>
    {section === 'general' ? <><Shortcut label="唤出 FlowHub" value={core.hotkey || 'Alt+Space'} taken={Object.values(core.scopeShortcuts)} onChange={v => setCore('hotkey', v)} /><Toggle label="登录后自动启动" checked={core.launchAtLogin === true} onChange={v => setCore('launchAtLogin', v)} /></> : null}
    {section === 'search' ? <>
      <Shortcut label="全部结果范围键" value={core.scopeShortcuts.all} allowBare taken={[core.hotkey, ...Object.entries(core.scopeShortcuts).filter(([k]) => k !== 'all').map(([, v]) => String(v))]} onChange={v => store.edit(c => { c.core.scopeShortcuts.all = v; })} />
      <div className="settings-search-heading"><span>搜索来源与顺序</span><Help label="搜索来源排序说明">拖动顺序把手，或聚焦把手后按 Alt + 上下方向键调整。点击范围键可重新录入，按 Delete 可清空。顺序只影响有关键词时的「全部」结果；2FA 和工具不参与排序。</Help></div>
      <div className="settings-search-columns" aria-hidden="true"><span>顺序</span><span>来源</span><span>启用</span><span>范围键</span></div>
      <div className="settings-search-list" role="list" aria-label="搜索来源与顺序">{searchPlugins.map(plugin => {
        const index = order.indexOf(plugin.id), sortable = index >= 0;
        const label = plugin.settingsName || plugin.name || names[plugin.id] || plugin.id;
        return <div role="listitem" className="settings-search-item" data-source={plugin.id} data-drop-target={dropSource === plugin.id && draggingSource !== plugin.id ? 'true' : undefined} key={plugin.id} onDragOver={e => { if (sortable && draggingSource) { e.preventDefault(); setDropSource(plugin.id); } }} onDrop={e => { e.preventDefault(); if (sortable && draggingSource) moveOrder(draggingSource, index); setDraggingSource(''); setDropSource(''); }}>
          <div className="settings-search-rank">{sortable ? <button type="button" className="settings-search-grip" draggable={!readonly() && !s.busy && !s.conflict} aria-label={`调整${label}顺序，当前第 ${index + 1} 位`} title="拖动排序；Alt + 上下方向键调整" onDragStart={e => { e.dataTransfer.setData('text/flowhub-search', plugin.id); e.dataTransfer.effectAllowed = 'move'; setDraggingSource(plugin.id); }} onDragEnd={() => { setDraggingSource(''); setDropSource(''); }} onKeyDown={e => { if (e.altKey && ['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'].includes(e.key)) { e.preventDefault(); moveOrder(plugin.id, index + (['ArrowUp', 'ArrowLeft'].includes(e.key) ? -1 : 1)); } }}><span aria-hidden="true">⠿</span><span>{index + 1}</span></button> : <span className="settings-search-not-ranked" aria-label="不参与排序">—</span>}</div>
          <div className="settings-search-name"><span>{label}</span>{plugin.available === false ? <small>{plugin.reason || (readonly() ? '浏览器预览不可用' : '当前环境不可用')}</small> : null}</div>
          <div className="settings-search-toggle"><Switch label={`启用${label}`} checked={c.plugins[plugin.id]?.enabled !== false} disabled={plugin.available === false} onChange={v => store.edit(c => { c.plugins[plugin.id] ||= { settings: {} }; c.plugins[plugin.id].enabled = v; })} /></div>
          <div className="settings-search-shortcut">{plugin.id in core.scopeShortcuts ? <Shortcut inline label={`${names[plugin.id] || label}范围键`} value={core.scopeShortcuts[plugin.id]} allowBare taken={[core.hotkey, ...Object.entries(core.scopeShortcuts).filter(([k]) => k !== plugin.id).map(([, v]) => String(v))]} onChange={v => store.edit(c => { c.core.scopeShortcuts[plugin.id] = v; })} /> : <span className="settings-search-none" aria-label="无范围快捷键">—</span>}</div>
        </div>;
      })}</div>
      <Toggle label="优先复用浏览器标签页" checked={core.reuseBrowserTabs === true} onChange={v => setCore('reuseBrowserTabs', v)} help="默认浏览器为 Arc 时复用完整链接相同的普通标签页；未找到则新建。" />
    </> : null}
    {section === 'network' ? <Choice label="代理检测适配器" value={c.plugins.tools.settings.proxyAdapter} options={[{ value: 'auto', label: '自动' }, { value: 'mihomo', label: 'Mihomo' }, { value: 'clash-rest', label: 'Clash REST' }, { value: 'system', label: '系统代理' }]} onChange={v => store.edit(c => { c.plugins.tools.settings.proxyAdapter = v; })} /> : null}
    {section === 'menubar' ? <>{Object.entries({ enabled: '显示 FlowHub 图标', showOpenLauncher: '打开启动器', showOpenSettings: '打开设置', showVersion: '显示版本', showQuit: '退出菜单', organizerEnabled: '启用菜单栏隐藏分区', collapseOnLaunch: '启动时收起隐藏分区' }).map(([key, label]) => <Toggle key={key} label={label} checked={core.menuBar[key] === true} disabled={key === 'collapseOnLaunch' ? !core.menuBar.organizerEnabled : ['showOpenLauncher', 'showOpenSettings', 'showVersion', 'showQuit'].includes(key) && !core.menuBar.enabled} onChange={v => setNested('menuBar', key, v)} />)}<Row label="菜单栏图标整理" help="展开后按住 ⌘，把待隐藏图标拖到箭头左侧；位置由 macOS 记忆。"><div className="flex flex-wrap gap-2"><Button disabled={!core.menuBar.organizerEnabled} onClick={() => void store.run(async () => { await write('toggleMenuBarItems'); })}>展开 / 收起</Button><Button onClick={() => void store.run(async () => { await write('requestMenuBarManagementPermission'); await store.refreshMenu(); })}>授权辅助功能</Button><Button onClick={() => void store.run(() => store.refreshMenu())}>扫描图标</Button></div></Row><p>{s.management.trusted ? '已授权 · 组合模式' : '未授权 · 原生模式'}</p>{s.menuItems.map(item => <Row key={item.windowId ?? item.window_id} label={item.name || item.ownerName || item.owner_name || item.title || '菜单栏图标'}><Button disabled={!item.hideable || !core.menuBar.organizerEnabled || !s.management.trusted} onClick={() => void store.run(async () => { await write('setMenuBarItemHidden', Number(item.windowId ?? item.window_id), item.section !== 'alwaysHidden'); await store.refreshMenu(); })}>{item.section === 'alwaysHidden' ? '移到常显区' : '始终隐藏'}</Button></Row>)}</> : null}
    {section === 'notifications' ? <><Toggle label="允许通知" checked={core.notifications.enabled} onChange={v => setNested('notifications', 'enabled', v)} /><Toggle label="更新通知" checked={core.notifications.updates} disabled={!core.notifications.enabled} onChange={v => setNested('notifications', 'updates', v)} /><Row label="系统通知权限" help="权限由 macOS 系统设置 → 通知管理。"><Button disabled={!core.notifications.enabled} onClick={() => void store.run(async () => { await write('sendTestNotification'); store.notice('测试通知已发送'); })}>发送测试通知</Button></Row></> : null}
    {section === 'data' ? <DataPanel store={store} /> : null}
    {section === 'updates' ? <Updates store={store} /> : null}
  </section></fieldset></>;
}
export async function primaryUpdate(store: SettingsStore) {
  if (store.dirty) throw new Error('请先保存或放弃修改，再安装更新');
  if (store.snapshot().busy) return;
  store.patch({ busy: true });
  try { const result = await write('downloadAndInstallUpdate'); if (result.state) store.patch({ update: result.state }); }
  finally { store.patch({ busy: false }); }
}
function Updates({ store }: { store: SettingsStore }) {
  const s = useSettings(store), core = s.config!.core, update = s.update;
  const statusNames: Record<string, string> = { unsupported: '当前环境不支持更新', idle: '尚未检查', checking: '正在检查', available: '发现新版本', downloaded: '等待安装', downloading: '正在下载', installing: '正在安装', 'not-available': '暂无可用更新', 'up-to-date': '已是最新版本', error: '更新失败' };
  return <><div className="settings-update-summary"><div><strong>当前版本 {update.currentVersion || '预览版'}</strong><p role="status" className="fh-muted">{statusNames[update.status] || '尚未检查'}{update.availableVersion ? ` · ${update.availableVersion}` : ''}</p></div>{update.error ? <p role="alert">{update.error}</p> : null}{['downloading', 'installing'].includes(update.status) && typeof update.percent === 'number' ? <progress aria-label="更新进度" max={100} value={update.percent} /> : null}<div className="flex gap-2"><Button disabled={['checking', 'downloading', 'installing'].includes(update.status)} onClick={() => void store.run(async () => { const result = await write('checkForUpdates'); if (result.state) store.patch({ update: result.state }); })}>检查更新</Button>{['available', 'downloaded'].includes(update.status) ? <Button onClick={() => void store.run(() => primaryUpdate(store))}>{update.status === 'downloaded' ? '重启安装' : '下载并安装'}</Button> : null}</div></div><Toggle label="自动检查正式版" checked={core.autoUpdateCheck !== false} onChange={v => store.edit(c => { c.core.autoUpdateCheck = v; })} help="每 10 分钟检查正式版。" /><Toggle label="自动下载并重启安装" checked={core.autoUpdateInstall === true} onChange={v => store.edit(c => { c.core.autoUpdateInstall = v; })} /></>;
}
export function Tools({ store }: { store: SettingsStore }) { const s = useSettings(store), [counts, setCounts] = useState(() => host().FlowHubCommandStore?.counts()), [clearHistory, setClearHistory] = useState(false); return <><div className="settings-tools-grid">{Object.entries(tools).map(([key, label]) => <Toggle key={key} label={label} checked={s.config!.plugins.tools.settings[key] !== false} onChange={v => store.edit(c => { c.plugins.tools.settings[key] = v; })} />)}</div><Row label="命令历史与参数模板" help="ping、curl、端口历史共用此开关；包含凭据的查询不会写入历史。"><p>{counts ? `${counts.total} 条历史 · ${counts.templates} 个模板` : '暂无历史'}</p><Button onClick={() => setClearHistory(true)}>清空历史与模板</Button></Row>{clearHistory ? <Dialog title="清空命令历史与模板" busy={false} onClose={() => setClearHistory(false)}><p>此操作不能撤销。历史和参数模板将同时清空。</p><Button onClick={() => { if (readonly()) return; host().FlowHubCommandStore?.clearAll(); setCounts(host().FlowHubCommandStore?.counts()); setClearHistory(false); }}>确认清空</Button></Dialog> : null}</>; }
export function Clipboard({ store }: { store: SettingsStore }) { const s = useSettings(store), config = s.config!.plugins.clipboard.settings; return <><Toggle label="暂停采集" checked={config.capturePaused === true} onChange={v => store.edit(c => { c.plugins.clipboard.settings.capturePaused = v; })} help="暂停保留历史搜索和粘贴，恢复不会补采暂停期间的内容；请保存成功后再复制敏感内容。" /><Toggle label="敏感标记保护" checked={config.protectSensitive !== false} onChange={v => store.edit(c => { c.plugins.clipboard.settings.protectSensitive = v; })} help="按 macOS 剪贴板类型标记跳过隐藏、临时和自动生成内容；未标记的密码仍可能被记录，历史不会自动脱敏。" />{['retentionDays', 'maxRecords', 'maxBytes'].map((key, i) => <TextField key={key} label={['留存天数', '最多记录条数', '逻辑内容容量（字节）'][i]} type="number" min={0} max={i === 0 ? 3650 : undefined} value={config[key] ?? (i === 0 ? 30 : 0)} onChange={v => store.edit(c => { c.plugins.clipboard.settings[key] = clipboardLimit(v, key); })} help="0 表示不限制；保存后生效，超限按最近复制时间淘汰。逻辑容量不等于数据库物理大小。" />)}{hasExclusions(s.config) || hasExclusions(s.saved) ? <Row label="旧来源应用排除列表" help="平台无法可靠识别来源应用；旧列表会保守阻止所有新采集。清空列表将连同其他草稿一起保存。"><Button onClick={() => void store.run(async () => { store.edit(c => { c.plugins.clipboard.settings.excludedApps = []; c.plugins.clipboard.settings.excludedBundleIds = []; }); await store.save(); })}>清空旧列表并保存</Button></Row> : null}<PathControl store={store} storage /></>; }
