(() => {
  const $=s=>document.querySelector(s), invoke=window.__TAURI__?.core?.invoke;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let layout={boards:[{id:'default',title:'默认布局',cards:[]}],active:'default',pinned:false},sources=[],editing=false,dragged='',naming='new',saving=false;
  let editingCard=null,gesture=null,suppressClick=false,menuCard=null,menuLeaveTimer=null,menuWatchTimer=null,menuGeneration=0;
  const cancelMenuLeave=()=>{clearTimeout(menuLeaveTimer);menuLeaveTimer=null;};
  const closeMenu=()=>{cancelMenuLeave();clearTimeout(menuWatchTimer);menuGeneration++;menu.hidden=true;menuCard=null;};
  const insideMenu=target=>!!target&&(menu.contains(target)||menuCard?.contains(target));
  const scheduleMenuLeave=()=>{if(!menu.hidden&&menuLeaveTimer===null)menuLeaveTimer=setTimeout(()=>{menuLeaveTimer=null;closeMenu();},180);};
  const trackMenuPosition=(x,y)=>{if(menu.hidden)return;const contains=el=>{if(!el?.isConnected)return false;const r=el.getBoundingClientRect();return x>=r.left&&x<r.right&&y>=r.top&&y<r.bottom;};if(contains(menu)||contains(menuCard))cancelMenuLeave();else scheduleMenuLeave();};
  // WKWebView can miss leave events when crossing a transparent desktop window.
  // Only watch while a pointer-opened menu is visible; ignore stale IPC replies.
  function watchMenu(){clearTimeout(menuWatchTimer);const generation=++menuGeneration;if(!invoke)return;const check=async()=>{try{const p=await invoke('plugin_canvas_api',{action:'cursor',payload:{}});if(generation!==menuGeneration||menu.hidden)return;trackMenuPosition(p.x,p.y);}catch{}if(generation===menuGeneration&&!menu.hidden)menuWatchTimer=setTimeout(check,120);};menuWatchTimer=setTimeout(check,120);}
  const menu=document.createElement('div');menu.className='card-menu';menu.hidden=true;menu.setAttribute('role','menu');document.body.append(menu);
  function openCard(c){const title=c.title||sources.find(s=>s.id===c.plugin)?.snapshot?.rows?.find(r=>r.id===c.row)?.name||'监控详情';if(!c.row){$('#notice').textContent='请先在编辑组件中选择目标机器';return;}if(invoke)invoke('plugin_canvas_api',{action:'detail',payload:{plugin:c.plugin,row:c.row,title}}).catch(e=>$('#notice').textContent=String(e));else location.href='widget-detail.html?'+new URLSearchParams({plugin:c.plugin,row:c.row,title});}
  function context(c,x,y){menu.innerHTML='<button role="menuitem" data-action="open">打开详情</button><button role="menuitem" data-action="edit">编辑组件</button><button role="menuitem" data-action="remove">移除组件</button>';cancelMenuLeave();menuCard=document.querySelector(`[data-id="${CSS.escape(c.id)}"]`);menu.hidden=false;menu.style.left=Math.max(8,Math.min(x,innerWidth-176))+'px';menu.style.top=Math.max(8,Math.min(y,innerHeight-180))+'px';menu.onclick=e=>{const a=e.target.dataset.action;closeMenu();if(a==='open')openCard(c);if(a==='edit')add(c);if(a==='remove'){board().cards=board().cards.filter(i=>i.id!==c.id);commit();}};menu.querySelector('button').focus();}
  document.addEventListener('pointerdown',e=>{if(!menu.contains(e.target))closeMenu();},true);
  document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
  document.addEventListener('pointermove',e=>trackMenuPosition(e.clientX,e.clientY),true);
  document.addEventListener('mousemove',e=>trackMenuPosition(e.clientX,e.clientY),true);
  document.addEventListener('pointerout',e=>{if(menu.hidden)return;if(!e.relatedTarget)closeMenu();else if(!insideMenu(e.relatedTarget))scheduleMenuLeave();},true);
  window.addEventListener('pagehide',closeMenu);
  document.documentElement.addEventListener('pointerleave',closeMenu);
  window.addEventListener('blur',closeMenu);
  document.addEventListener('visibilitychange',()=>{if(document.hidden)closeMenu();});
  document.addEventListener('focusin',e=>{if(!menu.hidden&&!menu.contains(e.target)&&!menuCard?.contains(e.target))closeMenu();});
  document.addEventListener('scroll',e=>{if(!menu.contains(e.target))closeMenu();},true);
  $('#canvas').oncontextmenu=e=>{const c=board().cards.find(c=>c.id===e.target.closest('.card')?.dataset.id);if(c){e.preventDefault();closeMenu();context(c,e.clientX,e.clientY);watchMenu();}};
  $('#canvas').addEventListener('keydown',e=>{const c=board().cards.find(c=>c.id===e.target.dataset.id);if(!c)return;if(e.key==='Enter'){e.preventDefault();openCard(c);}if(e.key==='ContextMenu'||(e.shiftKey&&e.key==='F10')){e.preventDefault();const r=e.target.getBoundingClientRect();context(c,r.left+20,r.top+20);}});
  const board=()=>layout.boards.find(b=>b.id===layout.active),uid=()=>crypto.randomUUID();
  const labels={healthy:'正常',error:'异常',stale:'已过期',unknown:'未采集'};
  document.body.classList.toggle('preview',!invoke);
  function gauges(row,metrics){return '<div class="gauges">'+[['cpu','CPU'],['memory','内存'],['disk','磁盘']].filter(([key])=>metrics.includes(key)).map(([key,label])=>{const value=row.values?.[key],valid=typeof value==='number'&&Number.isFinite(value);return `<div class="gauge ${value>=85?'warning':''}"><svg viewBox="0 0 100 86" role="img" aria-label="${label} ${valid?value.toFixed(1)+'%':'无数据'}"><path class="track" d="M 16 67 A 39 39 0 1 1 84 67" pathLength="100"/><path class="fill" d="M 16 67 A 39 39 0 1 1 84 67" pathLength="100" stroke-dasharray="${valid?Math.max(0,Math.min(100,value)):0} 100"/><text x="50" y="48">${valid?Math.round(value)+'%':'—'}</text><text class="unit" x="50" y="65">${label}</text></svg></div>`;}).join('')+'</div>';}
  function migrate(){
    if(layout.version>=2)return;
    if(layout.boards.some(b=>b.cards.some(c=>c.view==='list'&&!sources.find(s=>s.id===c.plugin)?.snapshot)))return;
    for(const b of layout.boards){let spare=32-b.cards.length;b.cards=b.cards.flatMap(c=>{const rows=sources.find(s=>s.id===c.plugin)?.snapshot?.rows||[];if(c.view!=='list'||!rows.length||rows.length-1>spare)return [c];spare-=rows.length-1;return rows.map(r=>({...c,id:uid(),row:r.id,title:r.name,view:'machine',size:'medium'}));});}
    layout.version=2;save().catch(()=>{});
  }
  let saveTail=Promise.resolve();
  function save(){const snapshot=structuredClone(layout);const persist=async()=>{if(!invoke){localStorage.setItem('flowhub-canvas-preview',JSON.stringify(snapshot));return;}saving=true;try{await invoke('plugin_canvas_api',{action:'save',payload:snapshot});$('#notice').textContent='';fitSurface();}catch(e){$('#notice').textContent='保存失败：'+e;throw e;}finally{saving=false;}};saveTail=saveTail.catch(()=>{}).then(persist);return saveTail;}
  function network(card,row){if(card.view!=='machine')return '';return '<span class="header-network">'+[['tx','↑','上传'],['rx','↓','下载']].filter(([k])=>card.metrics?.includes(k)).map(([k,arrow,label])=>{const v=row?.values?.[k],text=Number.isFinite(v)?(v>=1000?(v/1000).toFixed(1)+' MB/s':v.toFixed(1)+' KB/s'):'—';return `<span title="${label}速率" aria-label="${label}速率 ${text}">${arrow} ${text}</span>`;}).join('')+'</span>';}
  function content(card,source){
    if(!source)return '<p class="empty">插件未启用 · 布局已保留</p>';
    const snapshot=source.snapshot;if(!snapshot)return '<p class="empty">正在等待插件状态…</p>';
    if(snapshot.error)return `<p class="empty">${esc(snapshot.error)}</p>`;
    const rows=Array.isArray(snapshot.rows)?snapshot.rows:[];
    if(card.view==='machine'){const row=rows.find(r=>r.id===card.row);if(!row)return '<p class="empty">目标已移除或尚无数据</p>';const metrics=card.metrics||['cpu','memory','disk'];return gauges(row,metrics)+`<div class="widget-foot"><span class="${Object.hasOwn(labels,row.status)?row.status:'unknown'}">● ${labels[row.status]||'未知'}</span><span>${row.at?esc(new Date(row.at).toLocaleTimeString()):'未采集'}</span></div>`+(['load','uptime'].some(k=>metrics.includes(k))?'<div class="bottom-metrics">'+[['load','负载',''],['uptime','运行','天']].filter(([k])=>metrics.includes(k)).map(([k,label,unit])=>`<span>${label} ${Number.isFinite(row.values?.[k])?(k==='uptime'?(row.values[k]/86400).toFixed(1):row.values[k].toFixed(1)):'—'}${unit}</span>`).join('')+'</div>':'');}
    if(card.view==='overview')return `<div class="overview-total">${rows.length}<small>个实例</small></div><div class="overview-status"><span class="healthy">● ${rows.filter(r=>r.status==='healthy').length} 正常</span><span class="error">${rows.filter(r=>r.status==='error'||r.status==='stale').length} 异常 / 过期</span></div>`;
    const visible=card.view==='alerts'?rows.filter(r=>r.status!=='healthy'):rows;
    return visible.map(r=>`<div class="row"><div class="row-head"><b>${esc(r.name)}</b><span class="${Object.hasOwn(labels,r.status)?r.status:'unknown'}">● ${labels[r.status]||'未知'}</span></div><div class="values">${Object.entries(r.values||{}).filter(([,v])=>typeof v==='number'&&Number.isFinite(v)).slice(0,5).map(([k,v])=>`<span><small>${esc({cpu:'CPU',memory:'内存',disk:'磁盘',load:'负载',uptime:'运行秒数'}[k]||k)}</small>${esc(v.toLocaleString(undefined,{maximumFractionDigits:1}))}${['cpu','memory','disk'].includes(k)?'%':''}</span>`).join('')}</div><time>${r.at?esc(new Date(r.at).toLocaleTimeString()):'尚无采集数据'}</time></div>`).join('')||`<p class="empty">${card.view==='alerts'?'当前没有异常':'暂无状态数据'}</p>`;
  }
  function positionCards(moving=null,wanted=null){const positions=WidgetLayout.arrange(board().cards,moving,wanted);for(const p of positions){const c=board().cards.find(c=>c.id===p.id);c.x=p.x;c.y=p.y;c.break_before=false;const n=document.querySelector(`[data-id="${CSS.escape(p.id)}"]`);if(n){n.style.left=p.x+'px';n.style.top=p.y+'px';}}const width=Math.max(320,...positions.map(p=>p.x+p.w)),height=Math.max(120,...positions.map(p=>p.y+p.h));$('#canvas').style.width=width+'px';$('#canvas').style.height=height+'px';return {width,height};}
  let fitted='';function fitSurface(){if(!invoke||gesture||document.querySelector('dialog[open]'))return;const width=Math.max(360,$('#canvas').offsetWidth+32,document.querySelector('header').scrollWidth+32),height=$('#canvas').offsetTop+$('#canvas').offsetHeight+16,key=width+':'+height;if(key===fitted)return;fitted=key;invoke('plugin_canvas_api',{action:'fit',payload:{width,height}}).catch(()=>{fitted='';});}
  function render(){
    closeMenu();document.body.classList.toggle('editing-mode',editing);
    if(layout.boards.length>1){document.querySelector('header .tools').prepend($('#boards'));$('#boards').setAttribute('aria-label','切换组件布局');}
    $('#boards').innerHTML=layout.boards.map(b=>`<option value="${esc(b.id)}">${esc(b.title)}</option>`).join('');$('#boards').value=layout.active;$('#pin').checked=layout.pinned;$('#removeBoard').disabled=layout.boards.length===1;
    $('#canvas').classList.toggle('editing',editing);$('#edit').textContent=editing?'完成编辑':'编辑布局';
    $('#canvas').innerHTML=board().cards.map(c=>{const source=sources.find(s=>s.id===c.plugin),row=source?.snapshot?.rows?.find(r=>r.id===c.row);return `<article tabindex="0" aria-label="${esc(c.title||row?.name||source?.title||c.plugin)}，点击打开详情，右键编辑" class="card ${c.size}" data-id="${esc(c.id)}" style="width:${Number(c.width)||({small:184,medium:384,large:384}[c.size])}px;height:${Number(c.height)||({small:184,medium:184,large:384}[c.size])}px"><div class="card-head" draggable="false"><div><small>${esc(source?.title||c.plugin)} / ${{machine:'METRICS',list:'STATUS',overview:'OVERVIEW',alerts:'ATTENTION'}[c.view]}</small><h2>${esc(c.title||row?.name||source?.title||c.plugin)}</h2></div>${network(c,row)}</div><div class="card-body">${content(c,source)}</div><div class="editor"><button data-move="-1" aria-label="前移">←</button><button data-move="1" aria-label="后移">→</button><button data-remove>移除</button></div><button class="resize-handle" aria-label="调整组件大小" title="拖动缩放；方向键微调" data-resize>⌟</button></article>`;}).join('')||'<div class="blank"><h2>把常看的信息，放在一起。</h2><p>从已安装的插件中添加组件，保存自己的桌面布局。</p><button class="primary" data-add>＋ 添加第一个组件</button></div>';
    positionCards();fitSurface();
  }
  function add(card=null){ editingCard=card?.id||null;$('#source').innerHTML=sources.map(s=>`<option value="${esc(s.id)}">${esc(s.title)}</option>`).join('');if(!sources.length){$('#notice').textContent='请先启用提供状态组件的插件';return;}if(card){$('#source').value=card.plugin;}$('#view').value='machine';document.querySelectorAll('#metricFields input').forEach(i=>i.checked=(card?.metrics||['cpu','memory','disk']).includes(i.value));$('#cardTitle').value=card?.title||'';updateRows();if(card)$('#widgetRow').value=card.row||'';$('#picker h2').textContent=card?'编辑组件':'添加组件';$('#widgetForm button[type=submit]').textContent=card?'保存修改':'添加到画布';window.FlowHubSelects?.sync();$('#picker').showModal();if(invoke)invoke('plugin_canvas_api',{action:'fit',payload:{width:Math.max(innerWidth,360),height:Math.max(innerHeight,560)}}).catch(()=>{}); }
  $('#picker').addEventListener('close',()=>{fitted='';fitSurface();});
  const commit=()=>{render();save().catch(()=>{});};
  function updateRows(){const rows=sources.find(s=>s.id===$('#source').value)?.snapshot?.rows||[];$('#widgetRow').innerHTML=rows.map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join('');$('#rowField').hidden=$('#view').value!=='machine';}
  $('#source').onchange=updateRows;$('#view').onchange=updateRows;
  $('#dragSurface').onmousedown=e=>{if(e.button===0&&invoke)invoke('plugin_canvas_api',{action:'drag',payload:{}}).catch(()=>{});};
  $('#closeSurface').onclick=()=>{if(invoke)invoke('plugin_canvas_api',{action:'close',payload:{}}).catch(e=>$('#notice').textContent=String(e));};
  $('#edit').onclick=()=>{editing=!editing;render();};$('#add').onclick=()=>add();
  $('#boards').onchange=e=>{layout.active=e.target.value;commit();};$('#pin').onchange=e=>{layout.pinned=e.target.checked;commit();};
  $('#widgetForm').onsubmit=e=>{e.preventDefault();if($('#view').value==='machine'&&!$('#widgetRow').value)return;if(!editingCard&&board().cards.length>=32){$('#notice').textContent='每个布局最多 32 个组件';return;}const metrics=[...document.querySelectorAll('#metricFields input:checked')].map(i=>i.value);if(!metrics.length){document.querySelector('#metricFields input').focus();return;}const previous=board().cards.find(c=>c.id===editingCard);const next={id:editingCard||uid(),plugin:$('#source').value,title:$('#cardTitle').value.trim(),metrics,view:$('#view').value,size:previous?.size||'medium',row:$('#view').value==='machine'?$('#widgetRow').value:null};if(previous){if(previous.size===next.size){next.width=previous.width;next.height=previous.height;}Object.assign(previous,{width:null,height:null},next);}else board().cards.push(next);$('#picker').close();commit();};
  $('#newBoard').onclick=()=>{naming='new';$('#nameTitle').textContent='新建布局';$('#boardName').value='';$('#nameDialog').showModal();};$('#rename').onclick=()=>{naming='rename';$('#nameTitle').textContent='重命名布局';$('#boardName').value=board().title;$('#nameDialog').showModal();};
  $('#nameForm').onsubmit=e=>{e.preventDefault();const title=$('#boardName').value.trim();if(!title)return;if(naming==='new'){if(layout.boards.length>=12)return;const id=uid();layout.boards.push({id,title,cards:[]});layout.active=id;}else board().title=title;$('#nameDialog').close();commit();};
  $('#removeBoard').onclick=()=>$('#deleteDialog').showModal();$('#confirmDelete').onclick=()=>{if(layout.boards.length<2)return;layout.boards=layout.boards.filter(b=>b.id!==layout.active);layout.active=layout.boards[0].id;$('#deleteDialog').close();commit();};
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
  $('#canvas').onclick=e=>{if(suppressClick){suppressClick=false;return;}const button=e.target.closest('button');if(!button){if(e.target.closest('select'))return;const c=board().cards.find(c=>c.id===e.target.closest('.card')?.dataset.id);if(c){if(editing)add(c);else openCard(c);}return;}if(button.hasAttribute('data-add'))return add();if(button.dataset.open){if(invoke)invoke('plugin_status_api',{id:button.dataset.open,action:'plugin',payload:{}}).catch(e=>$('#notice').textContent=String(e));return;}const card=button.closest('.card'),items=board().cards,index=items.findIndex(c=>c.id===card?.dataset.id);if(index<0)return;if(button.hasAttribute('data-edit'))return add(items[index]);if(button.hasAttribute('data-resize'))return;if(button.hasAttribute('data-remove'))items.splice(index,1);else if(button.dataset.move){const next=index+Number(button.dataset.move);if(next>=0&&next<items.length)[items[index],items[next]]=[items[next],items[index]];}commit();};
  $('#canvas').ondragstart=e=>{if(!editing)return e.preventDefault();dragged=e.target.closest('.card').dataset.id;e.dataTransfer.setData('text/plain',dragged);};$('#canvas').ondragover=e=>{if(editing)e.preventDefault();};$('#canvas').ondrop=e=>{e.preventDefault();const target=e.target.closest('.card')?.dataset.id,items=board().cards,from=items.findIndex(c=>c.id===dragged),to=items.findIndex(c=>c.id===target);if(from>=0&&to>=0){const [card]=items.splice(from,1);items.splice(to,0,card);commit();}dragged='';};
  async function load(initial=false){if(saving||gesture||(!initial&&(editing||document.querySelector('dialog[open]')||!menu.hidden)))return;try{if(invoke){const data=await invoke('plugin_canvas_api',{action:'get',payload:{}});if(initial)layout=data.layout;sources=data.sources;}else if(initial){try{layout=JSON.parse(localStorage.getItem('flowhub-canvas-preview'))||layout;}catch{}sources=[{id:'demo-machines',title:'机器管理 · 模拟',snapshot:{rows:[{id:'a',name:'应用服务器',status:'healthy',values:{cpu:12,memory:36,disk:52},at:Date.now()},{id:'b',name:'任务节点',status:'stale',values:{cpu:63,memory:72},at:Date.now()-180000}]}}];$('#notice').textContent='浏览器预览 · 模拟数据，布局仅存当前浏览器';}if(!initial&&(gesture||!menu.hidden||document.querySelector('dialog[open]')))return;migrate();render();}catch(e){$('#notice').textContent=String(e);}}
  // Pointer events work in native WebViews without OS HTML drag/drop interception.
  $('#canvas').addEventListener('pointerdown',e=>{
    if(e.button!==0)return;
    const node=e.target.closest('.card'),resize=e.target.closest('[data-resize]');
    if(!node||(!resize&&e.target.closest('button,select,input')))return;
    const rect=node.getBoundingClientRect();
    gesture={node,id:node.dataset.id,resize:!!resize,x:e.clientX,y:e.clientY,width:rect.width,height:rect.height,left:node.offsetLeft,top:node.offsetTop,moved:false,target:null};
    node.setPointerCapture(e.pointerId);e.preventDefault();
  });
  $('#canvas').addEventListener('pointermove',e=>{
    if(!gesture)return;const g=gesture,dx=e.clientX-g.x,dy=e.clientY-g.y;
    if(Math.abs(dx)+Math.abs(dy)<4&&!g.moved)return;g.moved=true;
    if(g.resize){g.node.style.width=Math.round(Math.max(160,Math.min(1600,dx+g.width)))+'px';g.node.style.height=Math.round(Math.max(120,Math.min(1200,dy+g.height)))+'px';}
    else {g.node.classList.add('moving');g.wanted={x:Math.max(0,g.left+dx),y:Math.max(0,g.top+dy)};g.node.style.left=g.wanted.x+'px';g.node.style.top=g.wanted.y+'px';if(invoke&&Date.now()-(g.grown||0)>150&&(e.clientX>innerWidth-40||e.clientY>innerHeight-40)){g.grown=Date.now();fitted='';invoke('plugin_canvas_api',{action:'fit',payload:{width:innerWidth+(e.clientX>innerWidth-40?160:0),height:innerHeight+(e.clientY>innerHeight-40?140:0)}}).catch(()=>{});}}

  });
  const finish=(e,cancel=false)=>{if(!gesture)return;const g=gesture;gesture=null;if(g.node.hasPointerCapture(e.pointerId))g.node.releasePointerCapture(e.pointerId);if(!cancel&&g.moved){suppressClick=true;setTimeout(()=>suppressClick=false,100);const items=board().cards,card=items.find(c=>c.id===g.id);if(g.resize){card.width=parseInt(g.node.style.width);card.height=parseInt(g.node.style.height);}else {card.width=g.width;card.height=g.height;positionCards(card.id,g.wanted);}commit();}else if(cancel)render();};
  $('#canvas').addEventListener('pointerup',e=>finish(e));$('#canvas').addEventListener('pointercancel',e=>finish(e,true));
  $('#canvas').addEventListener('keydown',e=>{if(!e.target.matches('[data-resize]')||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const node=e.target.closest('.card'),card=board().cards.find(c=>c.id===node.dataset.id),rect=node.getBoundingClientRect();card.width=Math.max(160,Math.min(1600,(card.width||rect.width)+(e.key==='ArrowRight'?10:e.key==='ArrowLeft'?-10:0)));card.height=Math.max(160,Math.min(1200,(card.height||rect.height)+(e.key==='ArrowDown'?10:e.key==='ArrowUp'?-10:0)));commit();document.querySelector(`[data-id="${CSS.escape(card.id)}"] [data-resize]`)?.focus();});
  load(true);setInterval(()=>{if(!document.hidden)load();},15000);
})();
