import { createRoot } from 'react-dom/client';
import { Market } from './market/Market';
import { mountSettings } from './settings';
import './styles.css';
import { MenuBarPanel } from './surfaces/MenuBarPanel';
import { PluginStatus } from './surfaces/PluginStatus';
import { PluginDetail } from './surfaces/PluginDetail';
import './surfaces/styles.css';
import { mountSearch } from './search';
import { mountCanvas } from './canvas';
const search = document.getElementById('search-root');
if (search) mountSearch(search);
const canvas = document.getElementById('canvas-root');
if (canvas) mountCanvas(canvas);
const menu = document.getElementById('menu-bar-root');
if (menu) createRoot(menu).render(<MenuBarPanel />);
const status = document.getElementById('plugin-status-root');
if (status) createRoot(status).render(<PluginStatus />);
const detail = document.getElementById('plugin-detail-root');
if (detail) createRoot(detail).render(<PluginDetail />);
const market = document.getElementById('market-root');
if (market) createRoot(market).render(<Market />);
const settings = document.getElementById('settings-root');
if (settings) mountSettings(settings);
