//! Capture authorization, independent of storage and native clipboard access.
use serde_json::Value;

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct Policy {
    pub paused: bool,
    pub protect_sensitive: bool,
    pub excluded_apps: Vec<String>,
}
impl Policy {
    pub fn from_config(config: &Value) -> Self {
        let settings = &config["plugins"]["clipboard"]["settings"];
        let mut excluded_apps: Vec<String> = settings["excludedApps"]
            .as_array()
            .map(|values| {
                if values.iter().any(|value| !value.is_string()) {
                    return vec!["invalid exclusion configuration".into()];
                }
                values
                    .iter()
                    .filter_map(Value::as_str)
                    .map(str::trim)
                    .filter(|value| !value.is_empty())
                    .map(String::from)
                    .collect()
            })
            .unwrap_or_else(|| {
                if settings["excludedApps"].is_null() {
                    Vec::new()
                } else {
                    vec!["invalid exclusion configuration".into()]
                }
            });
        excluded_apps.sort();
        excluded_apps.dedup();
        Self {
            paused: settings["capturePaused"].as_bool().unwrap_or(false)
                || config["plugins"]["clipboard"]["enabled"].as_bool() == Some(false),
            protect_sensitive: settings["protectSensitive"].as_bool().unwrap_or(true),
            excluded_apps,
        }
    }
    pub fn permits_capture(&self) -> bool {
        // No supported platform currently provides authenticated clipboard writer
        // identity here. Frontmost apps and org.nspasteboard.source are not proof.
        // A configured exclusion therefore fails closed for unknown sources.
        !self.paused && self.excluded_apps.is_empty()
    }
    pub fn permits_formats(&self, formats: &[String]) -> bool {
        !self.protect_sensitive
            || !formats.iter().any(|format| {
                matches!(
                    format.as_str(),
                    "org.nspasteboard.ConcealedType"
                        | "org.nspasteboard.TransientType"
                        | "org.nspasteboard.AutoGeneratedType"
                        | "com.agilebits.onepassword"
                        | "de.petermaurer.TransientPasteboardType"
                        | "com.typeit4me.clipping"
                        | "Pasteboard generator type"
                )
            })
    }
}

pub(crate) struct Gate {
    pub policy: Policy,
    pub generation: u64,
    pub baseline: Option<isize>,
}
impl Gate {
    pub fn new() -> Self {
        Self {
            policy: Policy::from_config(&Value::Null),
            generation: 0,
            baseline: None,
        }
    }
    pub fn replace(&mut self, policy: Policy, baseline: Option<isize>) {
        self.generation = self.generation.wrapping_add(1);
        self.policy = policy;
        self.baseline = baseline;
    }
    pub fn permits_job(&self, generation: u64) -> bool {
        self.generation == generation && self.policy.permits_capture()
    }
    pub fn permits_revision(&self, revision: Option<isize>) -> bool {
        // Native revision support is required: never replay the resume baseline.
        revision.is_some() && revision != self.baseline && self.policy.permits_capture()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;
    #[test]
    fn pause_resume_discards_old_jobs_and_baseline() {
        let mut gate = Gate::new();
        let normal = Policy::from_config(&json!({}));
        gate.replace(normal.clone(), Some(10));
        assert!(!gate.permits_revision(Some(10)));
        assert!(gate.permits_revision(Some(11)));
        let queued = gate.generation;
        let mut paused = normal.clone();
        paused.paused = true;
        gate.replace(paused, Some(11));
        assert!(!gate.permits_job(queued));
        assert!(!gate.permits_revision(Some(12)));
        gate.replace(normal, Some(12));
        assert!(!gate.permits_job(queued));
        assert!(!gate.permits_revision(Some(12)));
        assert!(!gate.permits_revision(None));
        assert!(gate.permits_revision(Some(13)));
    }
    #[test]
    fn markers_apply_to_every_payload_without_secret_guessing() {
        let mut policy = Policy::from_config(&json!({}));
        for marker in [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "com.agilebits.onepassword",
        ] {
            assert!(!policy.permits_formats(&["public.png".into(), marker.into()]));
        }
        assert!(policy.permits_formats(&["public.utf8-plain-text".into()]));
        policy.protect_sensitive = false;
        assert!(policy.permits_formats(&["org.nspasteboard.ConcealedType".into()]));
    }
    #[test]
    fn unsupported_source_identity_fails_closed_and_normalizes_list() {
        let policy = Policy::from_config(
            &json!({"plugins":{"clipboard":{"settings":{"excludedApps":[" app.id ","app.id",""]}}}}),
        );
        assert_eq!(policy.excluded_apps, vec!["app.id"]);
        assert!(!policy.permits_capture());
        for invalid in [json!("app.id"), json!([123])] {
            assert!(!Policy::from_config(
                &json!({"plugins":{"clipboard":{"settings":{"excludedApps":invalid}}}})
            )
            .permits_capture());
        }
    }
}
