const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const s=fs.readFileSync(require('node:path').join(__dirname,'../ui/search.js'),'utf8');
let top=120,events=[];
const resultsEl={get scrollTop(){return top},set scrollTop(v){top=v;events.push('scroll')},set innerHTML(v){events.push('dom')}};
const ctx=vm.createContext({window:{},state:{config:{},scope:'clipboard',clipboardLoading:false,clipboardHasMore:false},resultsEl,matches:()=>[{}],renderResults:()=>'<div>row</div>',lastResultsHtml:'',windowedResults:false,esc:s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;')});
vm.runInContext(s.slice(s.indexOf('function renderMeasured('),s.indexOf('function revealActiveResult(')),ctx);
ctx.renderMeasured({preserveScroll:true});assert.deepEqual(events,['dom']);assert.equal(top,120);
events=[];ctx.lastResultsHtml='';ctx.renderMeasured();assert.deepEqual(events,['scroll','dom']);assert.equal(top,0);
vm.runInContext(s.slice(s.indexOf('function clipboardTextHtml('),s.indexOf('function isExpandableClipboard(')),ctx);
const original='<script>❌✅';const html=ctx.clipboardTextHtml(original);
assert(!html.includes('<script>'));assert.equal((html.match(/<svg/g)||[]).length,2);assert(html.includes('aria-label="❌"'));assert.equal(original,'<script>❌✅');
console.log('PASS: preserved scroll avoids post-DOM writes, reset precedes DOM, status preview escapes content and preserves source');
